# Generated by Django 3.0.2 on 2020-01-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200117_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='volume_choice',
            field=models.PositiveSmallIntegerField(choices=[(1, '생리대'), (2, '탐폰'), (3, '생리컵')]),
        ),
    ]
