# Generated by Django 3.0.2 on 2020-01-19 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hastag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('best_review', models.IntegerField()),
                ('score', models.IntegerField()),
                ('price', models.PositiveIntegerField()),
                ('count', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
                ('ingredients', models.TextField()),
                ('hashtag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Hastag')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('star', models.PositiveSmallIntegerField()),
                ('absorbency', models.PositiveSmallIntegerField()),
                ('anti_odour', models.PositiveSmallIntegerField()),
                ('sensitivity', models.PositiveSmallIntegerField()),
                ('comfort', models.PositiveSmallIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='RankingBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=4)),
                ('ranking', models.PositiveSmallIntegerField()),
                ('product_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
            ],
        ),
    ]
