# Generated by Django 3.0.2 on 2020-01-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200121_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nature_friendly',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
