# Generated by Django 3.0.2 on 2020-01-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_nature_friendly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_review',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
