# Generated by Django 3.0.2 on 2020-01-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200128_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Review'),
        ),
    ]
