# Generated by Django 3.0.3 on 2020-02-25 12:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='내용')),
                ('category', models.CharField(choices=[('notice', '공지사항'), ('event', '이벤트')], max_length=20, verbose_name='카테고리')),
                ('is_fixed', models.BooleanField(verbose_name='상단고정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
