# Generated by Django 3.0.3 on 2020-02-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200228_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_story_origin',
            old_name='category',
            new_name='sort',
        ),
    ]
